project_id = "epeitwkgbfabevxyznrh"

[auth]
site_url = "https://replii.ai"
additional_redirect_urls = [
  "replii://auth/callback",
  "replii://**",
  "http://127.0.0.1:42817/auth/callback",
  "http://localhost:42817/auth/callback",
  "http://localhost:3000/auth/callback",
  "http://localhost:3000/**",
  "https://replii.ai/auth/callback",
  "https://replii.ai/**",
]

[auth.email]
enable_confirmations = false

[auth.external.google]
enabled = true
client_id = "821453006387-t40vuplgvemi57kf3qhqp9gca4qmicd5.apps.googleusercontent.com"
secret = "env(SUPABASE_AUTH_EXTERNAL_GOOGLE_SECRET)"
